version: '3.8'

services:
  web:
    build:
      context: ./services/dj_queues
      dockerfile: ./compose/local/django/Dockerfile
    image: dj_queues
    # '/start' is the shell script used to run the service
    command: /start-django
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
      - django-postgres

  django-postgres:
    image: postgres:14-alpine
    volumes:
      - django-postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.django-postgres

  redis:
    image: redis:7.0.4
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: ./services/dj_queues
      dockerfile: ./compose/local/django/Dockerfile
    image: dj_queues_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.celery
    depends_on:
      - redis
      - django-postgres

  celery_beat:
    build:
      context: ./services/dj_queues
      dockerfile: ./compose/local/django/Dockerfile
    image: dj_queues_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
      - django-postgres

  flower:
    build:
      context: ./services/dj_queues
      dockerfile: ./compose/local/django/Dockerfile
    image: dj_queues_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - 5557:5555
    depends_on:
      - redis
      - django-postgres

volumes:
  django-postgres_data: