#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

echo "Connect to PostgreSQL ..."
while ! nc -z ${SQL_HOST} 5432; do
  sleep 0.1
  echo "Waiting for postgres ..."
done
echo "Found PostgreSQL"

echo "Migration to PostgreSQL..."
python manage.py migrate
echo "Migration finished"

python manage.py collectstatic --noinput

echo "Start server..."
# gunicorn dj_queues.wsgi:application --bind 0.0.0.0:8000 --log-level info --timeout 180  --workers 3
python manage.py runserver 0.0.0.0:8000