#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A dj_queues inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

# celery \
#     -A dj_queues flower \
#     --broker="${CELERY_BROKER}"

celery -A dj_queues  \
    --broker="${CELERY_BROKER}" \
    flower